apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: go-gke-pipe
description: main application pipeline
serialPipeline:
 stages:
 - targetId: testauto
   profiles: []
 - targetId: prodauto
   profiles: []
   strategy:
      canary:
        runtimeConfig:
          kubernetes:
            serviceNetworking:
              service: "basicgo"
              deployment: "basicgo"
        canaryDeployment:
          percentages: [25,50]
          verify: false
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: testauto
description: autopilot test cluster
gke:
 cluster: projects/gyucegok-alto/locations/us-east1/clusters/testauto
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: prodauto
description: autopilot prod cluster
requireApproval: true
gke:
 cluster: projects/gyucegok-alto/locations/us-east1/clusters/prodauto
